### ISSUE TITLE
Inheritance (sub class from Unit) no longer works

### ISSUE THREAD

**Issue by kreintjes** [olbrich/ruby-units#339]
In our app we create a sub class from Unit to apply some custom behaviour (https://github.com/olbrich/ruby-units/issues/240#issuecomment-977984852). This worked fine Ruby-Units 3.0 and before, but stopped working since Ruby-Units 4.0. If we try this now every .new call crashes with a `undefined method `keys' for nil:NilClass (NoMethodError)` error in `unit.rb:363:in `unit_regex`. This essentially breaks the functionality introduced in https://github.com/olbrich/ruby-units/pull/241.

To reproduce:

Add Ruby-Units 4.0.x to the Gemfile, and execute the following:

```
class ChildUnit < Unit; end
ChildUnit.new('1 l')
```

We are suspecting this has something to do with the refactor in https://github.com/olbrich/ruby-units/pull/274. Any suggestions on how to fix this would be welcome!

**Comment by olbrich** [comment]
@kreintjes Confirmed, I'll look into this soon.

**Comment by olbrich** [comment]
@kreintjes Please take a look at the associated PR and give it a shot. Let me know if it fixes your issues.  

Out of curiosity, what is motivating you to create a subclass?

**Comment by kreintjes** [comment]
@olbrich I tried it both in my sample project as well as in our real project and it both works great! Thanks for the quick fix!

We use a sub class of RubyUnits to override the `eliminate_terms` method with a simpler variant that does less simplification of the units after applying operations. E.g. when having Unit.new('10 l') / Unit.new('5 l') we leave this as 2 l/l instead of 2. See https://github.com/olbrich/ruby-units/issues/240 for details.

**Comment by kreintjes** [comment]
Nice you released this so quickly @olbrich! ❤️
