### PR TITLE
Inheritance (sub class from Unit) no longer works

### LINKED ISSUE #339: Inheritance (sub class from Unit) no longer works
In our app we create a sub class from Unit to apply some custom behaviour (https://github.com/olbrich/ruby-units/issues/240#issuecomment-977984852). This worked fine Ruby-Units 3.0 and before, but stopped working since Ruby-Units 4.0. If we try this now every .new call crashes with a `undefined method `keys' for nil:NilClass (NoMethodError)` error in `unit.rb:363:in `unit_regex`. This essentially breaks the functionality introduced in https://github.com/olbrich/ruby-units/pull/241.

To reproduce:

Add Ruby-Units 4.0.x to the Gemfile, and execute the following:

```
class ChildUnit < Unit; end
ChildUnit.new('1 l')
```

We are suspecting this has something to do with the refactor in https://github.com/olbrich/ruby-units/pull/274. Any suggestions on how to fix this would be welcome!

### PR DESCRIPTION
**Pull request by olbrich**
Fixes #339

Addresses initialization and set up that is needed by subclasses of RubyUnits::Unit.

### CODE REVIEW

**Comment by kreintjes** [comment]
Works great, thanks!
